FppEpitech/AREA

react-frontend/package-lock.json
react-frontend/package.json
react-frontend/src/pages/App/App.tsx
react-frontend/src/pages/Login/login.tsx
react-frontend/src/pages/Signup/signup.tsx

I created the login and register pages in HTML.
For the moment, pages are just here without working.

FEAT: Create a registerlogin page html (FNW-17)

---

react-frontend/package-lock.json
react-frontend/package.json
react-frontend/src/pages/App/App.tsx
react-frontend/src/pages/Explore/explore.tsx
react-frontend/src/pages/Login/login.tsx
react-frontend/src/pages/Signup/signup.tsx

I created the Explore page. This page aims to bring all services and plums for users:
For the moment this page is not linked to the back (and not very beautiful I know).
I created two lists to fill in the future with services and Plums cards:

FEAT: Create homepage explore html (FNW-21)

---

express-backend/index.ts
express-backend/package-lock.json
express-backend/package.json
express-backend/prisma/migrations/20241206114958_/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/account.ts
react-frontend/package-lock.json
react-frontend/package.json
react-frontend/src/pages/Login/login.tsx
react-frontend/src/pages/Signup/signup.tsx
react-frontend/src/services/auth/auth.tsx

This pull request includes several changes to both the backend and frontend of the application. The most important changes include adding CORS support to the backend, removing the `username` field from the `User` model, and implementing login and signup functionality in the frontend.
* Added CORS support:
* Imported and used the `cors` middleware in `express-backend/index.ts` to enable CORS. [[1]](diffhunk://#diff-28814191dab642f6bca2b5164f4bd6f86993f45a6f87400dbb27223f4eac4f98L4-R4) [[2]](diffhunk://#diff-28814191dab642f6bca2b5164f4bd6f86993f45a6f87400dbb27223f4eac4f98R13)
* Updated `express-backend/package-lock.json` and `express-backend/package.json` to include `cors` and `@types/cors` dependencies. [[1]](diffhunk://#diff-b753ef08965d4c61007ad23ad249d8932acd4cc9262c859192afdd07f8ff1b5dR …

FEAT: Register/login page link back (FNW-19)

---

express-backend/cron/CronClass.ts
express-backend/cron/CronInit.ts
express-backend/cron/UpdateCron.ts
express-backend/cron/WeatherCron.ts
express-backend/index.ts
express-backend/routes/plums.ts
express-backend/scrypt/createTriggerTemplate.ts
react-frontend/package-lock.json
react-frontend/package.json

I've created the script to add the template of weather in db.
I've created the endpoint to create plums.

FEAT: Add creation of plums (FNW-66)

---

express-backend/index.ts
express-backend/routes/action.ts
express-backend/routes/plums.ts
express-backend/routes/trigger.ts

I've created the differente endpoint to get the different template of action and trigger.

FEAT: Create route for action and trigger template (FNW-73)

---

express-backend/routes/plums.ts
express-backend/routes/spotify.ts

I've added the function to authenticate a user thanks to OAuth2 on spotify.
I've created the function to unhash a token given by the front.

FEAT: Added OAuth2 authentification spotify

---

express-backend/action/sendDiscordMessage.ts
express-backend/cron/UpdateCron.ts
express-backend/routes/plums.ts

This pull request introduces several changes to the `express-backend` project, focusing on enhancing the functionality of sending Discord messages, updating cron jobs, and adding a new route for deleting plums. The most important changes include modifying the `sendDiscordMessage` function, updating the cron job logic, and adding a new DELETE route in the `plums` router.
* [`express-backend/action/sendDiscordMessage.ts`](diffhunk://#diff-2dbc6a58aa7bed347fb851450907ad94ab9af9ee5614cdb29f0b1103ba081fbeL3-R13): Refactored the `sendDiscordMessage` function to accept a JSON string instead of an object, and added logic to parse and send the message correctly.
* [`express-backend/cron/UpdateCron.ts`](diffhunk://#diff-2664c37983c6d03fb86e0947fa5218ab4edf756e3bbd6f36eb482699e51e3c0bR2): Imported …

FEAT: Finish the link between the actions and the triggers

---

react-frontend/package-lock.json
react-frontend/src/components/Navbar/navbar.tsx
react-frontend/src/pages/App/App.tsx
react-frontend/src/pages/MyPlums/myPlums.tsx

This pull request includes changes to the `react-frontend` project, focusing on updating dependencies, adding a new route and component, and modifying existing components to incorporate the new route.
Dependency updates:
* [`react-frontend/package-lock.json`](diffhunk://#diff-a5805233f0dc92dbdb41108e67447080b9e3da063755d71fcc61d1470c0025aaR5573): Added `dev` flag to several dependencies, including `axios`, `form-data`, `proxy-from-env`, and `http-proxy-middleware`. [[1]](diffhunk://#diff-a5805233f0dc92dbdb41108e67447080b9e3da063755d71fcc61d1470c0025aaR5573) [[2]](diffhunk://#diff-a5805233f0dc92dbdb41108e67447080b9e3da063755d71fcc61d1470c0025aaR5584) [[3]](diffhunk://#diff-a5805233f0dc92dbdb41108e67447080b9e3da063755d71fcc61d1470c0025aaL14699-R14678) …

FEAT: Create the 'myPlums' page HTML (FNW-27)

---

react-frontend/android/.idea/deploymentTargetSelector.xml
react-frontend/src/components/IsMobile/isMobile.tsx
react-frontend/src/pages/Login/login.tsx
react-frontend/src/pages/Login/mobileLogin.tsx
react-frontend/src/pages/Signup/mobileSignup.tsx
react-frontend/src/pages/Signup/signup.tsx

This pull request introduces a set of changes aimed at improving the mobile user experience for the login and signup pages in the `react-frontend` project. The changes include adding mobile-specific components and a custom hook to detect mobile devices.
* **New Custom Hook for Mobile Detection:**
- [`react-frontend/src/components/IsMobile/isMobile.tsx`](diffhunk://#diff-347c08d594c734ece364cccf36fe6fa1ce81e188f0b8e3fd713c37bf33927ca6R1-R13): Added a custom hook `useIsMobile` to determine if the user is on a mobile device. This hook listens to window resize events to update its state.
* **Login Page Adjustments:**
- [`react-frontend/src/pages/Login/login.tsx`](diffhunk://#diff-0330cf7cc55b0e8d0467aac502084bd103ef31bb063772fe5c9cd3808b43ec6cR6-R7): Integrated the `useIsMobile` hook to …

FEAT: Handle responsive login/register page for mobile (FNW-80)

---

express-backend/index.ts
express-backend/prisma/migrations/20250106145241_/migration.sql
express-backend/prisma/schema.prisma
express-backend/scripts/createActionTemplate.ts
express-backend/scripts/createTriggerTemplate.ts
express-backend/scripts/initTemplates.ts

This pull request includes several changes to the `express-backend` project to improve template initialization and enforce unique constraints on database columns. The most important changes include adding a new initialization script, updating Prisma schema definitions, and refactoring existing scripts for better modularity.
Initialization improvements:
* [`express-backend/index.ts`](diffhunk://#diff-28814191dab642f6bca2b5164f4bd6f86993f45a6f87400dbb27223f4eac4f98R13-R20): Added the `initAllTemplates` function to initialize templates on startup.
* [`express-backend/scripts/initTemplates.ts`](diffhunk://#diff-043233a54a242b8606705fbf7c2488389f0d9dde8aaffebbb15be1eb1e496dbeR1-R37): Created a new script to initialize action and trigger templates, ensuring they are only added if they do not …

FEAT: Safe trigger & action creation at server start

---

.github/workflows/tests.yml
express-backend/package-lock.json
express-backend/package.json
express-backend/tests/clear_tests.sh
express-backend/tests/index.test.ts
express-backend/tests/test.sh

I added a run back end tests job to github ci actions and commented failing tests (and will create an issue so the back-end developpers fixes them).

FEAT: Add backend tests run to Github Actions (FNW-65)

---

react-frontend/src/pages/App/App.tsx
react-frontend/src/pages/Services/services.tsx

I added /service/{id} page HTML, with a temporary sample (discord)
Most of it will be updated when the backend routes will exists

FEAT: Service page HTML (FNW-102)

---

react-frontend/src/guards/authGuard.tsx
react-frontend/src/pages/App/App.tsx
react-frontend/src/services/auth/auth.tsx

Only logged users can now access to all pages.

FEAT: Secure routing for logged users (FNW-107)

---

express-backend/action/sendDiscordMessage.ts
express-backend/cron/CronClass.ts
express-backend/cron/UpdateCron.ts
express-backend/cron/WeatherCron.ts
express-backend/prisma/migrations/20250107140723_/migration.sql
express-backend/prisma/schema.prisma
express-backend/routes/plums.ts
express-backend/scripts/createActionTemplate.ts
express-backend/scripts/createTriggerTemplate.ts
express-backend/scripts/initTemplates.ts

This pull request includes several changes to the `express-backend` project, focusing on improving the handling of weather-related triggers, refactoring the code to use more specific weather conditions, and updating the database schema to enforce unique constraints. The most important changes include modifying the weather trigger functions, updating the database schema, and refactoring the `sendDiscordMessage` function.
Refactoring and improvements to weather-related triggers:
* [`express-backend/cron/WeatherCron.ts`](diffhunk://#diff-0346f0c8bf600beb81fb85373c4a4ef69ae93d1acf4a14e2aebd79a457e45622R50-R104): Replaced the `lessThan`, `greaterThan`, and `isEqual` functions with more specific weather condition functions (`pressure`, `temperature`, `cloudiness`, `windSpeed`, `humidity`, …

FEAT: Complete weather trigger and rework template

---

react-frontend/src/pages/Services/services.tsx

This pull request includes several enhancements and refactoring for the `Services` page in the `react-frontend` project. The changes focus on improving the UI and adding new features such as background color customization for services and sample data for testing.
UI Enhancements and Refactoring:
* [`react-frontend/src/pages/Services/services.tsx`](diffhunk://#diff-bdb05c84d2bc7b9d749786e247db30838da3c0965296d7cc201aba6c1a33a01dL23-R180): Updated the `ServiceDetail` component to include a background color for services and improved the layout with Tailwind CSS classes.
* [`react-frontend/src/pages/Services/services.tsx`](diffhunk://#diff-bdb05c84d2bc7b9d749786e247db30838da3c0965296d7cc201aba6c1a33a01dL23-R180): Refactored the `PlumCard` component to enhance the UI with Tailwind CSS classes …

FEAT: Service page css (FNW-103)

---

react-frontend/src/pages/App/App.tsx
react-frontend/src/pages/Create/create.tsx

This pull request includes changes to the `react-frontend` project to enhance the user experience by adding navigation and feedback functionality to the `CreatePage` and securing routes in the `App` component. The most important changes include the introduction of a `GuardedRoute` component, the addition of navigation after creating a plum, and the display of a success message.
Enhancements to route security and navigation:
* [`react-frontend/src/pages/App/App.tsx`](diffhunk://#diff-ab17fd47ad9f1232b48efdddd567a8b1eb9e26ba72759bb586df04e2a3bf93cdL16-R16): Replaced the `Login` component with the `GuardedRoute` component for the root path and the `Explore` path to secure these routes.
Improvements to `CreatePage`:
* [`react-frontend/src/pages/Create/create.tsx`](diffhunk://#diff-e558ab923957 …

FEAT: Event when create plum (FNW-112)

---

express-backend/prisma/schema.prisma
express-backend/routes/plums.ts

**_Mathieu please accept when this pr is tested and validated._**
This pull request includes changes to the `express-backend` project, specifically to the Prisma schema and the routes for handling plums. The most important changes include fixing a typo in the `User` model and adding a new route for updating plums.
Schema correction:
* [`express-backend/prisma/schema.prisma`](diffhunk://#diff-558eddc22a366fce62750ccb8f654524c0a2fc41ae8d967512840b2d7333d221L23-R23): Corrected a typo in the `User` model by changing `tiggers` to `triggers`.
New route addition:
* [`express-backend/routes/plums.ts`](diffhunk://#diff-d159aa94893c4d2ff54a59ffade2596f418e3d67f998efe36df8cd8ea848a232R192-R237): Added a new `PUT` route to update plums, which includes updating the plum's name, action, and trigger …

FEAT: update plum (FNW-114)

---

express-backend/scripts/createServices.ts
react-frontend/package.json
react-frontend/src/pages/Services/services.tsx

This pull request includes significant updates to the backend and frontend codebases to improve service creation and service display functionalities. The most important changes include modifying the service creation scripts, updating the proxy configuration, and enhancing the service detail page with dynamic data fetching and improved UI components.
Backend Changes:
* [`express-backend/scripts/createServices.ts`](diffhunk://#diff-0f22f9ec946865c0ef4c28bf67ccc705e2927eeaf5df0db090b1252cdf91dcd7L5-R20): Updated the service creation functions for Discord, OpenWeatherMap, and Mail to use new color codes and logo URLs. Improved error messages for better clarity. [[1]](diffhunk://#diff-0f22f9ec946865c0ef4c28bf67ccc705e2927eeaf5df0db090b1252cdf91dcd7L5-R20) …

FEAT: service page link back (FNW-104)

---

react-frontend/src/components/Create/workflowStep.tsx
react-frontend/src/components/Footer/Footer.tsx
react-frontend/src/components/Navbar/navbar.tsx
react-frontend/src/pages/Create/create.tsx
react-frontend/src/pages/MyPlums/myPlums.tsx

This pull request includes several changes to the `react-frontend` components and pages to improve the UI and add a new `Footer` component. The most important changes include the addition of the `Footer` component, modifications to the `CreatePage` layout, and updates to the `WorkflowStep` and `Navbar` components.
* [`react-frontend/src/components/Footer/Footer.tsx`](diffhunk://#diff-26444212cac140a8c870fd4b86d41cd931012d6d5b037edb1fd687088459990fR1-R11): Added a new `Footer` component that displays a footer bar with text.
* [`react-frontend/src/pages/Create/create.tsx`](diffhunk://#diff-e558ab923957e688b31c547bdc2e8b3c3952e587402f3d246fb7418e1d5d4884R7-R8): Imported and included the `Footer` component in the `CreatePage`. [[1]](diffhunk://#diff-e558ab923957e688b31c547bdc2e8b3c3952e587402f …

REFACTOR: Refont create page css (FNW-121)

---

express-backend/routes/about.ts

I've added the new triggers and actions of the new service to the file about.json accessible at this route like said in subject: http://localhost:8080/about.json

REFACTOR: I've updated the about.json

---

express-backend/routes/account.ts

This pull request includes significant updates to the `express-backend/routes/account.ts` file, focusing on enhancing security and adding a new endpoint for user account deletion. The most important changes include importing an authentication middleware, adding Swagger documentation, and implementing the new account deletion endpoint.
Security improvements:
* [`express-backend/routes/account.ts`](diffhunk://#diff-220c9cd36d156c6e2e198bbbe9b1b9c51233be46f1b31ee28c8fb67119589a83R6): Imported `authenticateToken` middleware to secure the new endpoint.
New features:
* [`express-backend/routes/account.ts`](diffhunk://#diff-220c9cd36d156c6e2e198bbbe9b1b9c51233be46f1b31ee28c8fb67119589a83R126-R177): Added Swagger documentation for the new `DELETE /account/deleteSelf` endpoint, which allows …

FEAT: Delete user route (FNW-136)

---

react-frontend/src/components/Create/workflowStep.tsx

I added a button to allow the user to clear the trigger/action that he is doing.
It's looking like this:

FEAT: Adding clear button (FNW-126)

---

react-frontend/src/services/auth/auth.tsx

I fixed a huge mistake during the register.
I forgot to add the token date to the local storage.

FIX: Added the token date when register (FNW-139)

---

express-backend/scripts/createActionTemplate.ts
express-backend/scripts/createTriggerTemplate.ts
react-frontend/src/pages/Explore/explore.tsx
react-frontend/src/pages/Services/services.tsx
react-frontend/src/services/Providers/providers.tsx

For a production DB, fetch didn't work so I replace by axios.

FIX: Replace fetch requests by axios (FNW-142)

---

react-frontend/src/pages/MyPlums/myPlums.tsx

I fixed filters in the myPlums page. 
The problem that each time, the getPlum function was called and reset the fiilter.

FIX: Filters working (FNW-145)

---

react-frontend/src/pages/Create/create.tsx
react-frontend/src/services/Plums/plums.tsx

The creation/update of plums display now if the request succeeded or failed.
For that I just check if the request failed or not.

FEAT: Handle succeeded or failed creation/update of plums (FNW-132)

---

express-backend/routes/spotify.ts

I fix the login redirection for web and mobile for Spotify.

REFACTOR: Differentiate spotify login for both web and mobile

---

react-frontend/src/components/Create/templatesTypes.tsx
react-frontend/src/components/Create/workflowSetup.tsx
react-frontend/src/components/Create/workflowStep.tsx
react-frontend/src/components/Explore/ExploreNavbar.tsx
react-frontend/src/components/Filter/Filter.tsx
react-frontend/src/components/Filter/ServiceDrop.tsx
react-frontend/src/components/Filter/StatusDrop.tsx
react-frontend/src/components/Footer/Footer.tsx
react-frontend/src/components/Navbar/navbar.tsx
react-frontend/src/pages/Contact/contact.tsx
react-frontend/src/pages/Create/create.tsx
react-frontend/src/pages/Explore/explore.tsx
react-frontend/src/pages/Login/login.tsx
react-frontend/src/pages/MyPlums/myPlums.tsx
react-frontend/src/pages/MyServices/myServices.tsx
react-frontend/src/pages/Services/services.tsx
react-frontend/src/pages/Signup/signup.tsx
react-frontend/src/pages/Welcome/welcome.tsx
react-frontend/src/services/auth/auth.tsx
react-frontend/tailwind.config.js

Here are examples of the darkmode theme:
This pull request includes several changes to improve the dark mode support in the `react-frontend/src/components/Create/templatesTypes.tsx` and `react-frontend/src/components/Create/workflowSetup.tsx` files. The changes primarily focus on updating the CSS classes to ensure proper styling in dark mode.
Dark mode support improvements:
* [`react-frontend/src/components/Create/templatesTypes.tsx`](diffhunk://#diff-7bf90aa133898d3c0adfafb1858be8ff1951f655d928e22882509dc5c9826151L23): Updated various components (`TemplateString`, `TemplateNumber`, `TemplateRadio`, `TemplateSearchDropdown`, `TemplateCron`) to use dark mode compatible CSS classes for borders, background colors, and text colors. [[1]](diffhunk://#diff-7bf90aa133898d3c0adfafb1858be8ff1951f65 …

FEAT: Dark mode CSS (FNW-117)

---

README.md

This pull request includes significant updates to the `README.md` file to enhance the project's documentation and provide a more structured overview of the project and its team.

FEAT: Complete the root readme
